### ISSUE TITLE
Texture Dump/Replacement in Gsdx9

### ISSUE THREAD

**Issue by MichelleHokawa** [Topaz-Reality/PCSX2-EX#4]
Could you make it work with GSdx9 instead of GSdx11?
the reason I ask this is because my computer doesn't work with dx11, only dx9 and dx10
![Request](https://user-images.githubusercontent.com/80962973/111789798-281ec600-8887-11eb-99d7-77f8b541a623.png)

**Comment by kurdischerjapane** [comment]
use Open GL

**Comment by Topaz-Reality** [comment]
Not the place for this. Pull #4199 is not a part of PCSX2-EX.
Closed.
