### ISSUE TITLE
Texture Dumping Midnight Club 3 DUB Edition Remix

### ISSUE THREAD

**Issue by danny199012** [Topaz-Reality/PCSX2-EX#6]
Not sure what the issue is i have the game set up correctly and runs fine im running at 1440p/2K
no issues at all but game causes emu to close when trying to view cars to buy at beginning of game i know the game works fine on normal Builds of PCSX2 also another note silly question but even having dump textures turned on where do they get dumped also if possible could we get option to select a directory?

running OpenGL at 2k default settings except 16:9 ratio and resolution
This is one game I've wanted to see a remastered version but unlikely to happen so was gonna just use Gigapixel to upscale textures and hopefully makes the game look way better 

putting game to 1080p fixed crash issue but not finding any dumped textures even after swapping to dx11

@Topaz-Reality Sorry to bother you but anyway I've been digging around in the games files and there's a textures.DAT if other games have this i think it would be easier to extract the .DAT for the textures and create a pack with them I Hope to hear back as i want to help contribute in making some texture packs

**Comment by Topaz-Reality** [comment]
Builds made in master are unsupported. An EX port is not yet made.
Until an EX port is made, no bug reports will be accepted.
Closed.
